03-sfc/04-vue-cli impl
js-tasks-ru/vue-20220809_aleksey34 pull request #4
Opened 2022-08-26 09:49 UTC by bezobraz1e

2022-08-26 09:50 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-08-27 21:07 UTC, ShGKme requested changes
Разделение на компоненты в `TheToaster` получилось не очень удачным. Требуется сделать `UiToast` таким, чтобы его можно было использовать, как самостоятельный независимый компонент.

Остальные задачи приняты

2022-08-27 21:07 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiIcon.vue
> +
Эти стили не являются стилями компонента иконки, как такого. Это не вариация иконки, а конкретный вариант использования иконки. Поэтому эти стили должны быть там, где таким образом иконка и используется - в компоненте тоста.

2022-08-27 21:07 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +</template>
Этот компонент нельзя использовать самостоятельно, кроме как в конкретном месте - внутри `TheToaster`. Это просто иконка с текстом рядом. И общий блок тоста, и стили тоста остались в `TheToaster`.

2022-08-27 21:07 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +    },
Обычно параметры лучше передавать отдельно, не оборачивая их в ещё один объект. Параметры (пропсы) фактически уже объект пар ключ (имя пропса) - значение.

Передача отдельных параметров удобнее пользователю компонента: видны отдельные параметры и их типы без дополнительной документации и TypeScript, не нужно обязательно оборачивать во объект.

```html
<ui-toast :toast="{ icon: 'error', message: 'error' }" />
<ui-toast icon="error" message="error" />
``

2022-08-27 21:07 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
Здесь хорошо подходит метод some: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2022-08-29 10:47 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-29 10:47 UTC, bezobraz1e commented on 04-vue-cli/02-TheToaster/components/UiIcon.vue
> +
вынес в UiToast

2022-08-29 10:49 UTC, bezobraz1e commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
исправил

2022-08-29 10:49 UTC, bezobraz1e commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +</template>
исрпвил

2022-08-29 10:51 UTC, bezobraz1e commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +    },
поменял на отдельные параметры

2022-08-29 12:21 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-08-29 19:31 UTC, ShGKme approved these changes
Все задачи приняты

2022-08-29 19:31 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +}
И параметры, и события, и даже просто свойствао бъектов/классов обычно называют проще, без названия самой сущности в свойстве этой сущности. В данном случае - без `toast`. Так имя будет проще, короче.

Когда родитель устанавливает параметр, например,  `message` у `UiToast`, он итак знает, что это сообщение тоста тоста, без уточнения `toastMessage`.

Как с объектами обычно не добавляют имя объекта (класса) в имена свойств:

```
const User = {
  userName: '',
  userAge: 42,
  userEmail: '...'
};
```

2022-08-29 19:32 UTC, merged